package com.hemebiotech.analytics;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

public class SymptomsProcess {

    /**
     * Counts occurrences of symptoms and writes the result into a new file "result.out"
     */

    public TreeMap<String, Integer> count(List<String> symptoms) {

        /**
         * Create a Treemap that will count occurrences of each symptom read in the List returned by the ReadSymptomDataFromFile method
         * @param symptoms listing of all symptoms obtained from a data source generated by the ReadSymptomDataFromFile method
         * @param symptomsCountMap read the symptoms List, put the symptom to key and implements the value each time the symptom is read
         * @return the symptomsCountMap TreeMap with symptoms for keys and nb of occurrence for value
         */

        TreeMap<String, Integer> symptomsCountMap = new TreeMap<>();

        for (String symptom : symptoms) {
            if (symptomsCountMap.containsKey(symptom))
                symptomsCountMap.put(symptom, symptomsCountMap.get(symptom) + 1);
            else
                symptomsCountMap.put(symptom, 1);
        }
        return symptomsCountMap;
    }

    /**
     * Writes the symptomsCountMap into a "result.out" file
     * @param symptomsCountAndSorted TreeMap created to structure the symptomsCountMap
     */
    public void writeResult(TreeMap<String, Integer> symptomsCountAndSorted) {

        FileWriter writer = null;
        BufferedWriter bw = null;

        try {
            writer = new FileWriter("result.out", true);
            bw = new BufferedWriter(writer);
            for (Map.Entry<String, Integer> entry : symptomsCountAndSorted.entrySet()) {
                String key = entry.getKey();
                Integer value = entry.getValue();

                bw.write(key + " => " + value);
                bw.newLine();
            }
        } catch (IOException oe) {
            System.err.format("Erreur lors de l'écriture du fichier");
        } finally {
            if (writer != null){
                try {
                    writer.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            if (bw != null){
                try {
                    bw.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }
}